
media:
  input: assets/actus
  output: /assets/actus

content:
  - name: actualites
    label: Actualités
    type: file
    path: actualites-2026.json
    format: json

    list:
      collapsible: true
      summary: "{date} — {titre}"

    fields:
      - name: date
        label: Date
        type: date
        required: true

      - name: titre
        label: Titre
        type: string
        required: true

      - name: resume
        label: Texte de l'actualité
        type: text
        required: true

      - name: images
        label: Photos
        type: image
        list: true
        required: false

      - name: lien
        label: Lien Facebook
        type: string
        required: false